/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.vistas;

import colegio.Materia;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Caro_Z
 */
public class FormularioDeMaterias extends javax.swing.JInternalFrame {

    private HashSet<Materia> materias;

    /**
     * Creates new form FormularioDeMaterias
     *
     * @param <error>
     */
    public FormularioDeMaterias(HashSet<Materia> materias) {
        initComponents();
        this.setSize(550, 550);
        this.materias = materias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtAnio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jBtnNuevo = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(null);

        jtxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCodigoFocusLost(evt);
            }
        });
        jtxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtCodigo);
        jtxtCodigo.setBounds(310, 110, 142, 20);

        jtxtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusLost(evt);
            }
        });
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtNombre);
        jtxtNombre.setBounds(310, 180, 142, 20);

        jtxtAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtAnioFocusLost(evt);
            }
        });
        jtxtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAnioKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtAnio);
        jtxtAnio.setBounds(310, 260, 142, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORMULARIO DE MATERIAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(99, 11, 288, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO DE MATERIA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 179, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE DE LA MATERIA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 193, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AÑO AL QUE PERTENECE:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 260, 193, 17);

        jBtnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnGuardar.setText("GUARDAR");
        jBtnGuardar.setEnabled(false);
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnGuardar);
        jBtnGuardar.setBounds(60, 350, 110, 40);

        jBtnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnNuevo.setText("NUEVO");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNuevo);
        jBtnNuevo.setBounds(220, 350, 120, 40);

        jBtnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSalir.setText("SALIR");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir);
        jBtnSalir.setBounds(380, 350, 110, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-formulario.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-16, -4, 620, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:

        String nom = jtxtNombre.getText();
        int cod = Integer.parseInt(jtxtCodigo.getText());
        int anio = Integer.parseInt(jtxtAnio.getText());

        Materia mat = new Materia(cod, nom, anio);
        materias.add(mat);
        JOptionPane.showMessageDialog(this, " Se agregó la materia ");
        desactivar();


    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        activar();
        jBtnGuardar.setEnabled(false);

    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jtxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodigoKeyTyped
        // TODO add your handling code here:

        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
//            JOptionPane.showMessageDialog(this,"El dato CODIGO debe ser numérico");
            evt.consume();
        }
    }//GEN-LAST:event_jtxtCodigoKeyTyped

    private void jtxtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAnioKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }

    }//GEN-LAST:event_jtxtAnioKeyTyped

    private void jtxtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombreFocusLost
        // TODO add your handling code here:
        if (jtxtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Nombre debe estar completo");
            jtxtNombre.requestFocus();
        }

    }//GEN-LAST:event_jtxtNombreFocusLost

    private void jtxtAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtAnioFocusLost
        // TODO add your handling code here:
        if (jtxtAnio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Año debe estar completo");
            jtxtAnio.requestFocus();
        }
        if (!jtxtNombre.getText().isEmpty()) {
            if (!jtxtAnio.getText().isEmpty()) {
                if (!jtxtCodigo.getText().isEmpty()) {
                    jBtnGuardar.setEnabled(true);
                }
            }
        }

    }//GEN-LAST:event_jtxtAnioFocusLost

    private void jtxtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCodigoFocusLost
        // TODO add your handling code here:

        if (jtxtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Código debe estar completo");
            jtxtCodigo.requestFocus();
        }

    }//GEN-LAST:event_jtxtCodigoFocusLost

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void desactivar() {
        jtxtCodigo.setEnabled(false);
        jtxtNombre.setEnabled(false);
        jtxtAnio.setEnabled(false);

    }

    private void activar() {
        jtxtCodigo.setEnabled(true);
        jtxtNombre.setEnabled(true);
        jtxtAnio.setEnabled(true);

    }

    private void limpiar() {
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jtxtAnio.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtxtAnio;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
