/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.vistas;

import colegio.Alumno;
import colegio.Materia;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Caro_Z
 */
public class FormularioDeInscrip extends javax.swing.JInternalFrame {

    private HashSet<Materia> materias;
    private HashSet<Alumno> alumnos;

    public FormularioDeInscrip(HashSet<Alumno> alumnos, HashSet<Materia> materias) {
        initComponents();
        this.setSize(550, 550);
        this.materias = materias;
        this.alumnos = alumnos;
        agregarMateriaCombo(); //llena el combo
        agregarAlumnoCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();
        jBtnInscribir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboAlumno = new javax.swing.JComboBox<>();
        jComboMateria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(536, 441, 0, 0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORMULARIO DE INSCRIPCION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 60, 321, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ELIJA UN ALUMNO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 170, 167, 17);

        jBtnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSalir.setText("SALIR");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir);
        jBtnSalir.setBounds(345, 338, 110, 40);

        jBtnInscribir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnInscribir.setText("INSCRIBIR");
        jBtnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInscribirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnInscribir);
        jBtnInscribir.setBounds(107, 338, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ELIJA UNA MATERIA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 230, 167, 17);

        jComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboAlumno);
        jComboAlumno.setBounds(320, 170, 176, 20);

        jComboMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMateria);
        jComboMateria.setBounds(320, 230, 176, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-formulario.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 0, 610, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlumnoActionPerformed

    private void jComboMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMateriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboMateriaActionPerformed

    private void jBtnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInscribirActionPerformed
        // TODO add your handling code here:
        // alumno seleccionado en el items, se castea de Object a Alumno/ Materia
        try {
            Alumno seleccionado = (Alumno) jComboAlumno.getSelectedItem();

            Materia seleccionada = (Materia) jComboMateria.getSelectedItem();
            seleccionado.agregarMateria(seleccionada);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " ");
        }

    }//GEN-LAST:event_jBtnInscribirActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void agregarMateriaCombo() {
        for (Materia m : materias) {
            jComboMateria.addItem(m);
        }

    }

    private void agregarAlumnoCombo() {

        for (Alumno a1 : alumnos) {

            jComboAlumno.addItem(a1);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnInscribir;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<Alumno> jComboAlumno;
    private javax.swing.JComboBox<Materia> jComboMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
